In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Numpy and Pandas.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "EgrClAlpC8s-",
        "colab_type": "text"
      },
      "source": [
        "# Python Basic operations"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ZuQjJSf9C0ko",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "0289376d-5b39-4737-9ea4-c0e8897fc8f3"
      },
      "source": [
        "class Disease:\n",
        "  def __init__(self, disease = 'Depression'):\n",
        "    self.type = disease\n",
        "    \n",
        "  def getName(self):\n",
        "    print(\"Mental Health Diseases: {0}\".format(self.type))\n",
        "\n",
        "d1 = Disease('Social Anxiety Disorder')\n",
        "d1.getName()"
      ],
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Mental Health Diseases: Social Anxiety Disorder\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "kTyrcThEDCIU",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "65d7db92-cd4f-448b-bb59-a1cd1a011845"
      },
      "source": [
        "# Try Catch Block\n",
        "# The try block will generate a NameError, because x is not defined:\n",
        "\n",
        "try:\n",
        "  print(y)\n",
        "except NameError:\n",
        "  print(\"Well, the variable y is not defined\")\n",
        "except:\n",
        "  print(\"OMG, Something else went wrong\")\n"
      ],
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Well, the variable y is not defined\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "iGbKigYzD4rM",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 51
        },
        "outputId": "c1270b91-ce4b-42b2-b8f0-53edf3c0e7b6"
      },
      "source": [
        "\n",
        "try:\n",
        " Value = int(input(\"Type a number between 1 and 10:\"))\n",
        "except ValueError:\n",
        "  print(\"You must type a number between 1 and 10!\")\n",
        "else:\n",
        "  if (Value > 0) and (Value <= 10):\n",
        "      print(\"You typed: \", Value)\n",
        "  else:\n",
        "      print(\"The value you typed is incorrect!\")\n"
      ],
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Type a number between 1 and 10:333\n",
            "The value you typed is incorrect!\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "xNPYSP_aDxgz",
        "colab_type": "text"
      },
      "source": [
        "# Numpy Array Basics"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "GVMckxhaDsrH",
        "colab_type": "code",
        "outputId": "e2a06eb3-b689-4e96-e66c-aefb8f740a53",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 170
        }
      },
      "source": [
        "# importing numpy\n",
        "import numpy as np\n",
        "\n",
        "# Defining 1D array\n",
        "my1DArray = np.array([1, 8, 27, 64])\n",
        "print(my1DArray)\n",
        "\n",
        "# Defining and printing 2D array\n",
        "my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])\n",
        "print(my2DArray)\n",
        "\n",
        "#Defining and printing 3D array\n",
        "my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]])\n",
        "print(my3Darray)\n",
        "\n"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[ 1  8 27 64]\n",
            "[[ 1  2  3  4]\n",
            " [ 2  4  9 16]\n",
            " [ 4  8 18 32]]\n",
            "[[[ 1  2  3  4]\n",
            "  [ 5  6  7  8]]\n",
            "\n",
            " [[ 1  2  3  4]\n",
            "  [ 9 10 11 12]]]\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "FOHcYUkkF2u-",
        "colab_type": "code",
        "outputId": "a504d500-aeb6-40cc-aa63-0590900b2a77",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 85
        }
      },
      "source": [
        "# Print out memory address\n",
        "print(my2DArray.data)\n",
        "\n",
        "# Print the shape of array\n",
        "print(my2DArray.shape)\n",
        "\n",
        "# Print out the data type of the array\n",
        "print(my2DArray.dtype)\n",
        "\n",
        "\"\"\"\n",
        "Print the stride of the array.\n",
        "\n",
        "So what is stride of array?  It is the number of locations in memory between \n",
        "beginnings of successive array elements, measured in bytes or in units of the\n",
        "size of the array's elements\n",
        "\"\"\"\n",
        "print(my2DArray.strides)"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "<memory at 0x7f0477c79048>\n",
            "(3, 4)\n",
            "int64\n",
            "(32, 8)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "_tan6CTdpvH3",
        "colab_type": "text"
      },
      "source": [
        "# Array using numpy built-in functions"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "hXg80w6Wpsqd",
        "colab_type": "code",
        "outputId": "c19ade55-5dcd-4477-c7bb-f57e566d6cd4",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 306
        }
      },
      "source": [
        "# Array of ones\n",
        "ones = np.ones((3,4))\n",
        "print(ones)\n",
        "\n",
        "# Array of zeros\n",
        "zeros = np.zeros((2,3,4),dtype=np.int16)\n",
        "print(zeros)\n",
        "\n",
        "# Array with random values\n",
        "np.random.random((2,2))\n",
        "\n",
        "# Empty array\n",
        "emptyArray = np.empty((3,2))\n",
        "print(emptyArray)\n",
        "\n",
        "# Full array\n",
        "fullArray = np.full((2,2),7)\n",
        "print(fullArray)\n",
        "\n",
        "# Array of evenly-spaced values\n",
        "evenSpacedArray = np.arange(10,25,5)\n",
        "print(evenSpacedArray)\n",
        "\n",
        "# Array of evenly-spaced values\n",
        "evenSpacedArray2 = np.linspace(0,2,9)\n",
        "print(evenSpacedArray2)"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[[1. 1. 1. 1.]\n",
            " [1. 1. 1. 1.]\n",
            " [1. 1. 1. 1.]]\n",
            "[[[0 0 0 0]\n",
            "  [0 0 0 0]\n",
            "  [0 0 0 0]]\n",
            "\n",
            " [[0 0 0 0]\n",
            "  [0 0 0 0]\n",
            "  [0 0 0 0]]]\n",
            "[[2.18282866e-316 4.94065646e-324]\n",
            " [4.94065646e-324 0.00000000e+000]\n",
            " [0.00000000e+000 0.00000000e+000]]\n",
            "[[7 7]\n",
            " [7 7]]\n",
            "[10 15 20]\n",
            "[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "0VMNmT2BqjtF",
        "colab_type": "text"
      },
      "source": [
        "# Numpy array and file operations"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "87k4xazaqeD7",
        "colab_type": "code",
        "outputId": "37d23b09-4830-4330-c115-73a0cf87f0bd",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 139
        }
      },
      "source": [
        "# Save a numpy array into file\n",
        "x = np.arange(0.0,50.0,1.0)\n",
        "np.savetxt('data.out', x, delimiter=',')\n",
        "\n",
        "# Loading numpy array from text\n",
        "z = np.loadtxt('data.out', unpack=True)\n",
        "print(z)\n",
        "\n",
        "# Loading numpy array using genfromtxt method\n",
        "my_array2 = np.genfromtxt('data.out',\n",
        "                      skip_header=1,\n",
        "                      filling_values=-999)\n",
        "print(my_array2)"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.\n",
            " 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.\n",
            " 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]\n",
            "[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.\n",
            " 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.\n",
            " 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "laHX9HM7rd_h",
        "colab_type": "text"
      },
      "source": [
        "# Inspecting numpy arrays\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "hus66cO8rlm6",
        "colab_type": "code",
        "outputId": "8944dcdd-e851-4d07-bac7-4b11b1539b27",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 204
        }
      },
      "source": [
        "# Print the number of `my2DArray`'s dimensions\n",
        "print(my2DArray.ndim)\n",
        "\n",
        "# Print the number of `my2DArray`'s elements\n",
        "print(my2DArray.size)\n",
        "\n",
        "# Print information about `my2DArray`'s memory layout\n",
        "print(my2DArray.flags)\n",
        "\n",
        "# Print the length of one array element in bytes\n",
        "print(my2DArray.itemsize)\n",
        "\n",
        "# Print the total consumed bytes by `my2DArray`'s elements\n",
        "print(my2DArray.nbytes)"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "2\n",
            "12\n",
            "  C_CONTIGUOUS : True\n",
            "  F_CONTIGUOUS : False\n",
            "  OWNDATA : True\n",
            "  WRITEABLE : True\n",
            "  ALIGNED : True\n",
            "  WRITEBACKIFCOPY : False\n",
            "  UPDATEIFCOPY : False\n",
            "8\n",
            "96\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "IDr89W2wsHxj",
        "colab_type": "text"
      },
      "source": [
        "# Broadcasting in NumPy\n",
        "Broadcasting is a mechanism that permits `NumPy` to operate with arrays of different shapes when performing arithmetic operations. "
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "3YfESrnBr4Vz",
        "colab_type": "code",
        "outputId": "fdf4cae0-2c0e-4ced-b73f-d295bf9d6234",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 255
        }
      },
      "source": [
        "# Rule 1: Two dimensions are operatable if they are equal\n",
        "# Create an array of two dimension\n",
        "A =np.ones((6, 8))\n",
        "\n",
        "# Shape of A\n",
        "print(A.shape)\n",
        "\n",
        "# Create another array\n",
        "B = np.random.random((6,8))\n",
        "\n",
        "# Shape of B\n",
        "print(B.shape)\n",
        "\n",
        "# Sum of A and B, here the shape of both the matrix is same.\n",
        "print(A + B)"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "(6, 8)\n",
            "(6, 8)\n",
            "[[1.64613513 1.81218169 1.73277236 1.57617341 1.82402347 1.74772911\n",
            "  1.22843733 1.3993954 ]\n",
            " [1.4660033  1.33101593 1.14628103 1.15712902 1.66748722 1.37379544\n",
            "  1.62748161 1.7947295 ]\n",
            " [1.52599628 1.16567587 1.29470105 1.88796265 1.17581034 1.28402744\n",
            "  1.83282509 1.723289  ]\n",
            " [1.53980657 1.5358293  1.7890984  1.60113655 1.1386734  1.66052094\n",
            "  1.90500048 1.69306468]\n",
            " [1.81646704 1.30210421 1.59608074 1.87246912 1.57628331 1.68802283\n",
            "  1.24708731 1.43667052]\n",
            " [1.28634605 1.80769536 1.36572846 1.67252402 1.37322953 1.55805199\n",
            "  1.31193578 1.24668215]]\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "_Q2kSDgrtOYa",
        "colab_type": "code",
        "outputId": "1c03730e-e563-4ba4-d80b-fc4b8b185e02",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 170
        }
      },
      "source": [
        "# Rule 2: Two dimensions are also comptable when one of them is 1\n",
        "# Initialize `x`\n",
        "x = np.ones((3,4))\n",
        "print(x)\n",
        "\n",
        "# Check shape of `x`\n",
        "print(x.shape)\n",
        "\n",
        "# Initialize `y`\n",
        "y = np.arange(4)\n",
        "print(y)\n",
        "\n",
        "# Check shape of `y`\n",
        "print(y.shape)\n",
        "\n",
        "# Subtract `x` and `y`\n",
        "x - y "
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[[1. 1. 1. 1.]\n",
            " [1. 1. 1. 1.]\n",
            " [1. 1. 1. 1.]]\n",
            "(3, 4)\n",
            "[0 1 2 3]\n",
            "(4,)\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "array([[ 1.,  0., -1., -2.],\n",
              "       [ 1.,  0., -1., -2.],\n",
              "       [ 1.,  0., -1., -2.]])"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 7
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "qiHoL40gu4Kb",
        "colab_type": "code",
        "outputId": "b30df0c7-ff47-4a27-a347-13835a4f7c11",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "source": [
        "# Rule 3: Arrays can be broadcasted together if they are compatible in all dimensions\n",
        "\n",
        "x = np.ones((6,8))\n",
        "y = np.random.random((10, 1, 8))\n",
        "print(x + y)\n",
        "\n",
        "# Analytical question\n",
        "\"\"\"\n",
        "The dimensions of x(6,8) and y(10,1,8) are diffrent. However, it is possible \n",
        "to add them. Why is that? Also, change y(10,2,8) or y(10,1,4) it will \n",
        "give ValueError. Can you find out why?\n",
        "\"\"\""
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[[[1.02819824 1.6661437  1.25074124 1.98188502 1.67576215 1.1141407\n",
            "   1.05525764 1.89361746]\n",
            "  [1.02819824 1.6661437  1.25074124 1.98188502 1.67576215 1.1141407\n",
            "   1.05525764 1.89361746]\n",
            "  [1.02819824 1.6661437  1.25074124 1.98188502 1.67576215 1.1141407\n",
            "   1.05525764 1.89361746]\n",
            "  [1.02819824 1.6661437  1.25074124 1.98188502 1.67576215 1.1141407\n",
            "   1.05525764 1.89361746]\n",
            "  [1.02819824 1.6661437  1.25074124 1.98188502 1.67576215 1.1141407\n",
            "   1.05525764 1.89361746]\n",
            "  [1.02819824 1.6661437  1.25074124 1.98188502 1.67576215 1.1141407\n",
            "   1.05525764 1.89361746]]\n",
            "\n",
            " [[1.00519247 1.69467587 1.74493108 1.01649286 1.27603402 1.66879546\n",
            "   1.58778444 1.54278283]\n",
            "  [1.00519247 1.69467587 1.74493108 1.01649286 1.27603402 1.66879546\n",
            "   1.58778444 1.54278283]\n",
            "  [1.00519247 1.69467587 1.74493108 1.01649286 1.27603402 1.66879546\n",
            "   1.58778444 1.54278283]\n",
            "  [1.00519247 1.69467587 1.74493108 1.01649286 1.27603402 1.66879546\n",
            "   1.58778444 1.54278283]\n",
            "  [1.00519247 1.69467587 1.74493108 1.01649286 1.27603402 1.66879546\n",
            "   1.58778444 1.54278283]\n",
            "  [1.00519247 1.69467587 1.74493108 1.01649286 1.27603402 1.66879546\n",
            "   1.58778444 1.54278283]]\n",
            "\n",
            " [[1.17947289 1.19267446 1.09810831 1.15681195 1.79847927 1.99634615\n",
            "   1.34169815 1.4513772 ]\n",
            "  [1.17947289 1.19267446 1.09810831 1.15681195 1.79847927 1.99634615\n",
            "   1.34169815 1.4513772 ]\n",
            "  [1.17947289 1.19267446 1.09810831 1.15681195 1.79847927 1.99634615\n",
            "   1.34169815 1.4513772 ]\n",
            "  [1.17947289 1.19267446 1.09810831 1.15681195 1.79847927 1.99634615\n",
            "   1.34169815 1.4513772 ]\n",
            "  [1.17947289 1.19267446 1.09810831 1.15681195 1.79847927 1.99634615\n",
            "   1.34169815 1.4513772 ]\n",
            "  [1.17947289 1.19267446 1.09810831 1.15681195 1.79847927 1.99634615\n",
            "   1.34169815 1.4513772 ]]\n",
            "\n",
            " [[1.77657525 1.42893623 1.45768916 1.53390161 1.8934206  1.09735169\n",
            "   1.96093167 1.13343436]\n",
            "  [1.77657525 1.42893623 1.45768916 1.53390161 1.8934206  1.09735169\n",
            "   1.96093167 1.13343436]\n",
            "  [1.77657525 1.42893623 1.45768916 1.53390161 1.8934206  1.09735169\n",
            "   1.96093167 1.13343436]\n",
            "  [1.77657525 1.42893623 1.45768916 1.53390161 1.8934206  1.09735169\n",
            "   1.96093167 1.13343436]\n",
            "  [1.77657525 1.42893623 1.45768916 1.53390161 1.8934206  1.09735169\n",
            "   1.96093167 1.13343436]\n",
            "  [1.77657525 1.42893623 1.45768916 1.53390161 1.8934206  1.09735169\n",
            "   1.96093167 1.13343436]]\n",
            "\n",
            " [[1.44868984 1.88970484 1.82849956 1.67029951 1.77398273 1.29534318\n",
            "   1.85696243 1.01152638]\n",
            "  [1.44868984 1.88970484 1.82849956 1.67029951 1.77398273 1.29534318\n",
            "   1.85696243 1.01152638]\n",
            "  [1.44868984 1.88970484 1.82849956 1.67029951 1.77398273 1.29534318\n",
            "   1.85696243 1.01152638]\n",
            "  [1.44868984 1.88970484 1.82849956 1.67029951 1.77398273 1.29534318\n",
            "   1.85696243 1.01152638]\n",
            "  [1.44868984 1.88970484 1.82849956 1.67029951 1.77398273 1.29534318\n",
            "   1.85696243 1.01152638]\n",
            "  [1.44868984 1.88970484 1.82849956 1.67029951 1.77398273 1.29534318\n",
            "   1.85696243 1.01152638]]\n",
            "\n",
            " [[1.43203476 1.09782224 1.8650536

SyntaxError: unterminated string literal (detected at line 632) (1610729338.py, line 632)